#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成 FAR23_条款中文标题表.csv —— Part 23 全量条款中英对照。

术语口径（与民航适航行业中文习惯一致，可按需微调本表后重跑）：
  load=载荷 / limit load=限制载荷 / ultimate load=极限载荷 /
  factor of safety=安全系数 / gust=阵风 / maneuvering=机动 /
  damage tolerance=损伤容限 / fatigue evaluation=疲劳评定 /
  commuter category=通勤类 / normal, utility, acrobatic=正常类、实用类、特技类 /
  placard=标牌 / marking=标记 / Instructions for Continued Airworthiness=持续适航文件
"""
import csv
import os

ROOT = os.path.dirname(os.path.abspath(__file__))

# (分部, [(条款号, 英文标题, 中文标题), ...])
DATA = [
    ("(Authority citation)", [
        ("0.0", "Authority citation.", "授权引用（非实体条款）"),
    ]),
    ("Subpart A - General", [
        ("23.1", "Applicability.", "适用范围"),
        ("23.2", "Special retroactive requirements.", "特别追溯要求"),
        ("23.3", "Airplane categories.", "飞机类别"),
    ]),
    ("Subpart B - Flight", [
        ("23.21", "Proof of compliance.", "符合性验证"),
        ("23.23", "Load distribution limits.", "载荷分布限制"),
        ("23.25", "Weight limits.", "重量限制"),
        ("23.29", "Empty weight and corresponding center of gravity.", "空重与相应重心"),
        ("23.31", "Removable ballast.", "可卸配重"),
        ("23.33", "Propeller speed and pitch limits.", "螺旋桨转速与桨距限制"),
        ("23.45", "General.", "总则（性能）"),
        ("23.49", "Stalling speed.", "失速速度"),
        ("23.51", "Takeoff.", "起飞"),
        ("23.53", "Takeoff performance.", "起飞性能"),
        ("23.55", "Accelerate-stop distance.", "加速—停止距离"),
        ("23.57", "Takeoff path.", "起飞航迹"),
        ("23.59", "Takeoff distance and takeoff run.", "起飞距离与起飞滑跑"),
        ("23.61", "Takeoff flight path.", "起飞飞行航迹"),
        ("23.63", "Climb: general.", "爬升：总则"),
        ("23.65", "Climb: all engines operating.", "爬升：全部发动机工作"),
        ("23.66", "Takeoff climb: one engine inoperative.", "起飞爬升：一台发动机失效"),
        ("23.67", "Climb: one engine inoperative.", "爬升：一台发动机失效"),
        ("23.69", "(Enroute climb/descent.)", "航路爬升/下降"),
        ("23.71", "Glide: single-engine airplanes.", "滑翔：单发飞机"),
        ("23.73", "Reference landing approach speed.", "基准着陆进场速度"),
        ("23.75", "Landing [distance.]", "着陆[距离]"),
        ("23.77", "Balked landing.", "中断着陆（复飞）"),
        ("23.141", "General.", "总则（操纵性与机动性）"),
        ("23.143", "General.", "总则（操纵性）"),
        ("23.145", "Longitudinal control.", "纵向操纵"),
        ("23.147", "Directional and lateral control.", "航向与横向操纵"),
        ("23.149", "Minimum control speed.", "最小操纵速度"),
        ("23.151", "Acrobatic maneuvers.", "特技机动"),
        ("23.153", "Control during landings.", "着陆过程中的操纵"),
        ("23.155", "Elevator control force in maneuvers.", "机动中的升降舵操纵力"),
        ("23.157", "Rate of roll.", "滚转速率"),
        ("23.161", "Trim.", "配平"),
        ("23.171", "General.", "总则（稳定性）"),
        ("23.173", "Static longitudinal stability.", "纵向静稳定性"),
        ("23.175", "Demonstration of static longitudinal stability.", "纵向静稳定性的演示"),
        ("23.177", "Static directional and lateral stability.", "航向与横向静稳定性"),
        ("23.179", "Instrumented stick force measurements.", "驾驶杆力实测（仪表测量）"),
        ("23.181", "Dynamic longitudinal stability.", "纵向动稳定性"),
        ("23.201", "Wings level stall.", "机翼水平失速"),
        ("23.203", "Turning flight and accelerated turning stalls.", "转弯飞行与加速转弯失速"),
        ("23.205", "Removed.", "已删除"),
        ("23.207", "Stall warning.", "失速警告"),
        ("23.221", "Spinning.", "螺旋"),
        ("23.231", "Longitudinal stability and control.", "纵向稳定性与操纵"),
        ("23.233", "Directional stability and control.", "航向稳定性与操纵"),
        ("23.235", "Taxiing, [takeoff, and landing condition.]", "滑行、[起飞与着陆状态]"),
        ("23.237", "Operation on water.", "水面运行"),
        ("23.239", "Spray characteristics.", "喷溅特性"),
        ("23.251", "Vibration and buffeting.", "振动与抖振"),
        ("23.253", "High speed characteristics.", "高速特性"),
        ("23.255", "Out of trim characteristics.", "配平失效特性"),
    ]),
    ("Subpart C - Structure", [
        ("23.301", "Loads.", "载荷"),
        ("23.302", "Canard or tandem wing configurations.", "鸭式或串列翼构型"),
        ("23.303", "Factor of safety.", "安全系数"),
        ("23.305", "Strength and deformation.", "强度与变形"),
        ("23.307", "Proof of structure.", "结构验证"),
        ("23.321", "General.", "总则（飞行载荷）"),
        ("23.331", "Symmetrical flight conditions.", "对称飞行情况"),
        ("23.333", "Flight envelope.", "飞行包线"),
        ("23.335", "Design airspeeds.", "设计空速"),
        ("23.337", "Limit maneuvering load factors.", "机动限制载荷因数"),
        ("23.341", "Gust load factors.", "阵风载荷因数"),
        ("23.343", "Design fuel loads.", "设计燃油载荷"),
        ("23.345", "High lift devices.", "高升力装置"),
        ("23.347", "Unsymmetrical flight conditions.", "不对称飞行情况"),
        ("23.349", "Rolling conditions.", "滚转情况"),
        ("23.351", "Yawing conditions.", "偏航情况"),
        ("23.361", "Engine torque.", "发动机扭矩"),
        ("23.363", "Side load on engine mount.", "发动机安装架侧向载荷"),
        ("23.365", "Pressurized cabin loads.", "增压座舱载荷"),
        ("23.367", "Unsymmetrical loads due to engine failure.", "发动机失效引起的不对称载荷"),
        ("23.369", "Special conditions for rear lift truss.", "后升力桁架的专用条件"),
        ("23.371", "Gyroscopic and aerodynamic loads.", "陀螺载荷与气动载荷"),
        ("23.373", "Speed control devices.", "减速装置（限速装置）"),
        ("23.391", "Control surface loads.", "操纵面载荷"),
        ("23.393", "Loads parallel to hinge line.", "平行于铰链线的载荷"),
        ("23.395", "Control system.", "操纵系统载荷"),
        ("23.397", "Limit pilot forces.", "驾驶员限制操纵力"),
        ("23.399", "Dual control system.", "双套操纵系统"),
        ("23.405", "Secondary control system.", "辅助操纵系统"),
        ("23.407", "Trim tab effects.", "配平调整片效应"),
        ("23.409", "Tabs.", "调整片"),
        ("23.415", "Ground gust conditions.", "地面阵风情况"),
        ("23.421", "Balancing loads.", "平衡载荷"),
        ("23.423", "Maneuvering loads.", "机动载荷（辅助翼面）"),
        ("23.425", "Gust loads.", "阵风载荷（辅助翼面）"),
        ("23.427", "Unsymmetrical loads.", "不对称载荷（辅助翼面）"),
        ("23.441", "Maneuvering loads.", "机动载荷（尾翼）"),
        ("23.443", "Gust loads.", "阵风载荷（尾翼）"),
        ("23.445", "Outboard fins.", "外侧垂直安定面"),
        ("23.455", "Ailerons.", "副翼"),
        ("23.457", "Wing flaps.", "机翼襟翼"),
        ("23.459", "Special devices.", "特殊装置"),
        ("23.471", "General.", "总则（地面载荷）"),
        ("23.473", "Ground load conditions and assumptions.", "地面载荷情况与假设"),
        ("23.477", "Landing gear arrangement.", "起落架布置"),
        ("23.479", "Level landing conditions.", "水平着陆情况"),
        ("23.481", "Tail down landing conditions.", "尾部下沉着陆情况"),
        ("23.483", "One-wheel landing conditions.", "单轮着陆情况"),
        ("23.485", "Side load conditions.", "侧向载荷情况"),
        ("23.493", "Braked roll conditions.", "刹车滚滑情况"),
        ("23.497", "Supplementary conditions for tail wheels.", "尾轮的补充情况"),
        ("23.499", "Supplementary conditions for nose wheels.", "前轮的补充情况"),
        ("23.505", "Supplementary conditions for skiplanes.", "滑橇式飞机的补充情况"),
        ("23.507", "Jacking loads.", "顶升载荷"),
        ("23.509", "Towing loads.", "牵引载荷"),
        ("23.511", "Ground load; unsymmetrical loads on multiple-wheel units.", "地面载荷；多轮装置的不对称载荷"),
        ("23.521", "Water load conditions.", "水上载荷情况"),
        ("23.523", "Design weights and center of gravity positions.", "设计重量与重心位置"),
        ("23.525", "(Application of loads.)", "载荷的施加"),
        ("23.527", "(Hull and main float load factors.)", "船身与主浮筒载荷因数"),
        ("23.529", "(Hull and main float landing conditions.)", "船身与主浮筒着陆情况"),
        ("23.531", "(Hull and main float takeoff condition.)", "船身与主浮筒起飞情况"),
        ("23.533", "(Hull and main float bottom pressures.)", "船身与主浮筒底部压力"),
        ("23.535", "(Auxiliary float loads.)", "辅助浮筒载荷"),
        ("23.537", "Seawing loads.", "海翼载荷"),
        ("23.561", "General.", "总则（应急着陆）"),
        ("23.562", "Emergency landing dynamic conditions.", "应急着陆动力情况"),
        ("23.571", "Pressurized cabin.", "增压座舱（疲劳评定）"),
        ("23.572", "Wing and associated structure.", "机翼及相关结构"),
        ("23.573", "Damage tolerance and fatigue evaluation of structure.", "结构损伤容限与疲劳评定"),
        ("23.574", "Metallic damage tolerance and fatigue evaluation of commuter category airplanes.", "通勤类飞机金属结构损伤容限与疲劳评定"),
        ("23.575", "Inspections and other procedures.", "检查与其他程序"),
    ]),
    ("Subpart D - Design and Construction", [
        ("23.601", "General.", "总则（设计与构造）"),
        ("23.603", "Materials and workmanship.", "材料与工艺"),
        ("23.605", "Fabrication methods.", "制造方法"),
        ("23.607", "Self-locking nuts.", "自锁螺母"),
        ("23.609", "Protection of structure.", "结构防护"),
        ("23.611", "Accessibility [provisions.]", "可达性[规定]"),
        ("23.613", "Material strength properties and design values.", "材料强度性能与设计值"),
        ("23.615", "Removed.", "已删除"),
        ("23.617", "Interchangeability of seamwelded and seamless steel tubing.", "有缝焊钢管与无缝钢管的互换性"),
        ("23.619", "Special factors.", "特殊系数"),
        ("23.621", "Casting factors.", "铸件系数"),
        ("23.623", "Bearing factors.", "挤压系数（支承系数）"),
        ("23.625", "Fitting factors.", "接头系数"),
        ("23.627", "Fatigue strength.", "疲劳强度"),
        ("23.629", "Flutter.", "颤振"),
        ("23.641", "Proof of strength.", "强度验证"),
        ("23.643", "Deleted.", "已删除"),
        ("23.651", "Proof of strength.", "强度验证（操纵系统）"),
        ("23.655", "Installation.", "安装"),
        ("23.657", "Hinges.", "铰链"),
        ("23.659", "Mass balance.", "质量平衡"),
        ("23.671", "General.", "总则（操纵系统）"),
        ("23.672", "Stability augmentation and automatic and power-operated systems.", "稳定性增强系统与自动及动力驱动系统"),
        ("23.673", "Primary flight controls.", "主飞行操纵系统"),
        ("23.675", "Stops.", "限动器"),
        ("23.677", "Trim systems.", "配平系统"),
        ("23.679", "Control system locks.", "操纵系统锁"),
        ("23.681", "Limit load static tests.", "限制载荷静力试验"),
        ("23.683", "Operation tests.", "操作试验"),
        ("23.685", "Control system details.", "操纵系统细节"),
        ("23.687", "Spring devices.", "弹簧装置"),
        ("23.689", "Cable systems.", "钢索系统"),
        ("23.691", "Artificial stall barrier system.", "人工失速障碍系统"),
        ("23.693", "Joints.", "接头"),
        ("23.697", "Wing flap controls.", "襟翼操纵器件"),
        ("23.699", "Wing flap position indicator.", "襟翼位置指示器"),
        ("23.701", "Flap interconnection.", "襟翼联动"),
        ("23.703", "Takeoff warning system.", "起飞警告系统"),
        ("23.721", "General.", "总则（起落架）"),
        ("23.723", "Shock absorption tests.", "减震试验"),
        ("23.725", "Limit drop tests.", "限制落震试验"),
        ("23.726", "Ground load dynamic tests.", "地面载荷动力试验"),
        ("23.727", "Reserve energy absorption drop tests.", "储备能量吸收落震试验"),
        ("23.729", "Retracting mechanism.", "收放机构"),
        ("23.731", "Wheels.", "机轮"),
        ("23.733", "Tires.", "轮胎"),
        ("23.735", "Brakes.", "刹车"),
        ("23.737", "Skis.", "滑橇"),
        ("23.745", "Nose/Tail wheel steering.", "前轮/尾轮转向"),
        ("23.751", "Main float buoyancy.", "主浮筒浮力"),
        ("23.753", "Main float design.", "主浮筒设计"),
        ("23.755", "Hulls.", "船身"),
        ("23.757", "Auxiliary floats.", "辅助浮筒"),
        ("23.771", "Pilot compartment.", "驾驶舱"),
        ("23.773", "Pilot compartment view.", "驾驶舱视界"),
        ("23.775", "Windshields and windows.", "风挡与窗"),
        ("23.777", "Cockpit controls.", "驾驶舱操纵器件"),
        ("23.779", "Motion and effect of cockpit controls.", "驾驶舱操纵器件的运动与作用"),
        ("23.781", "Cockpit control knob shape.", "驾驶舱操纵旋钮形状"),
        ("23.783", "Doors.", "舱门"),
        ("23.785", "Seats, berths, safety belts, and harnesses.", "座椅、卧铺、安全带与束缚系统"),
        ("23.787", "Cargo compartments.", "货舱"),
        ("23.791", "Passenger information signs.", "旅客信息标识"),
        ("23.803", "Emergency evacuation.", "应急撤离"),
        ("23.805", "Flightcrew emergency exits.", "机组应急出口"),
        ("23.807", "Emergency exists.", "应急出口"),
        ("23.811", "Emergency exit marking.", "应急出口标识"),
        ("23.812", "Emergency lighting.", "应急照明"),
        ("23.813", "Emergency exit access.", "应急出口通道"),
        ("23.815", "Width of aisle.", "通道宽度"),
        ("23.831", "Ventilation.", "通风"),
        ("23.841", "Pressurized cabins.", "增压座舱"),
        ("23.843", "Pressurization tests.", "增压试验"),
        ("23.851", "Fire extinguishers.", "灭火器"),
        ("23.853", "Compartment interiors.", "舱内装饰材料"),
        ("23.855", "Cargo and baggage compartment fire protection.", "货舱与行李舱防火"),
        ("23.856", "Thermal/acoustic insulation materials.", "隔热/隔声材料"),
        ("23.859", "Combustion heater fire protection.", "燃烧加温器防火"),
        ("23.863", "Flammable fluid fire protection.", "可燃液体防火"),
        ("23.865", "Fire protection of flight controls, engine mounts, and other flight structure.", "飞行操纵系统、发动机安装架及其他飞行结构的防火"),
        ("23.867", "Electrical bonding and protection against lightning and static electricity.", "电气搭接与雷电、静电防护"),
        ("23.871", "Leveling means.", "调平装置"),
    ]),
    ("Subpart E - Powerplant", [
        ("23.901", "Installation.", "安装"),
        ("23.903", "Engines.", "发动机"),
        ("23.904", "Automatic power reserve system.", "自动功率储备系统（APR）"),
        ("23.905", "Propellers.", "螺旋桨"),
        ("23.907", "Propeller vibration and fatigue.", "螺旋桨振动与疲劳"),
        ("23.909", "Turbosuperchargers.", "涡轮增压器"),
        ("23.925", "Propeller clearance.", "螺旋桨间隙"),
        ("23.929", "Engine installation ice protection.", "发动机装置结冰防护"),
        ("23.933", "Reversing systems.", "反推/反桨系统"),
        ("23.934", "Turbojet and turbofan engine thrust reverser systems tests.", "涡喷与涡扇发动机反推系统试验"),
        ("23.937", "Turbopropeller-drag limiting systems.", "涡桨阻力限制系统"),
        ("23.939", "Powerplant operating characteristics.", "动力装置工作特性"),
        ("23.943", "Negative acceleration.", "负加速度"),
        ("23.951", "General.", "总则（燃油系统）"),
        ("23.953", "Fuel system independence.", "燃油系统独立性"),
        ("23.954", "Fuel system lightning protection.", "燃油系统雷电防护"),
        ("23.955", "Fuel flow.", "燃油流量"),
        ("23.957", "Flow between interconnected tanks.", "互通油箱之间的流动"),
        ("23.959", "Unusable fuel supply and fuel system operation on low fuel.", "不可用燃油量及低油量下的燃油系统工作"),
        ("23.961", "Fuel system hot weather operation.", "燃油系统高温天气工作"),
        ("23.963", "Fuel tanks: general.", "燃油箱：总则"),
        ("23.965", "Fuel tank tests.", "燃油箱试验"),
        ("23.967", "Fuel tank installation.", "燃油箱安装"),
        ("23.969", "Fuel tank expansion space.", "燃油箱膨胀空间"),
        ("23.971", "Fuel tank sump.", "燃油箱沉淀槽"),
        ("23.973", "Fuel tank filler connection.", "燃油箱加油接口"),
        ("23.975", "Fuel tank vents and carburetor vapor vents.", "燃油箱通气口与汽化器蒸汽通气口"),
        ("23.977", "Fuel tank outlet.", "燃油箱出油口"),
        ("23.979", "Pressure fueling systems.", "压力加油系统"),
        ("23.991", "Fuel pumps.", "燃油泵"),
        ("23.993", "Fuel system lines and fittings.", "燃油系统导管与接头"),
        ("23.994", "Fuel system components.", "燃油系统部件"),
        ("23.995", "Fuel valves and controls.", "燃油阀与控制器件"),
        ("23.997", "Fuel strainer or filter.", "燃油滤网或滤清器"),
        ("23.999", "Fuel system drains.", "燃油系统放油口"),
        ("23.1001", "Fuel jettisoning system.", "应急放油系统"),
        ("23.1011", "General.", "总则（滑油系统）"),
        ("23.1013", "Oil tanks.", "滑油箱"),
        ("23.1015", "Oil tank tests.", "滑油箱试验"),
        ("23.1017", "Oil lines and fittings.", "滑油导管与接头"),
        ("23.1019", "Oil strainer or filter.", "滑油滤网或滤清器"),
        ("23.1021", "Oil system drains.", "滑油系统放油口"),
        ("23.1023", "Oil radiators.", "滑油散热器"),
        ("23.1027", "Propeller feathering system.", "螺旋桨顺桨系统"),
        ("23.1041", "General.", "总则（冷却）"),
        ("23.1043", "Cooling tests.", "冷却试验"),
        ("23.1045", "Cooling test procedures for [turbine engine powered airplanes.]", "[涡轮发动机飞机]的冷却试验程序"),
        ("23.1047", "Cooling test procedures for reciprocating engine powered airplanes.", "活塞式发动机飞机的冷却试验程序"),
        ("23.1061", "Installation.", "安装（冷却液系统）"),
        ("23.1063", "Coolant tank tests.", "冷却液箱试验"),
        ("23.1091", "Air induction system.", "空气进气系统"),
        ("23.1093", "Induction system icing protection.", "进气系统结冰防护"),
        ("23.1095", "Carburetor deicing fluid flow rate.", "汽化器防冰液流量"),
        ("23.1097", "Carburetor deicing fluid system capacity.", "汽化器防冰液系统容量"),
        ("23.1099", "Carburetor deicing fluid system detail design.", "汽化器防冰液系统详细设计"),
        ("23.1101", "Carburetor air preheater design.", "汽化器空气预热器设计"),
        ("23.1103", "Induction system ducts.", "进气系统导管"),
        ("23.1105", "Induction system screens.", "进气系统滤网"),
        ("23.1107", "Induction system filters.", "进气系统滤清器"),
        ("23.1109", "Turbocharger bleed air system.", "涡轮增压器引气系统"),
        ("23.1111", "Turbine engine bleed air system.", "涡轮发动机引气系统"),
        ("23.1121", "General.", "总则（排气系统）"),
        ("23.1123", "Exhaust [system.]", "排气[系统]"),
        ("23.1125", "Exhaust heat exchangers.", "排气热交换器"),
        ("23.1141", "Powerplant controls: general.", "动力装置控制器件：总则"),
        ("23.1142", "Auxiliary power unit controls.", "辅助动力装置控制器件"),
        ("23.1143", "Engine controls.", "发动机控制器件"),
        ("23.1145", "Ignition switches.", "点火开关"),
        ("23.1147", "Mixture controls.", "混合比控制器件"),
        ("23.1149", "Propeller speed and pitch controls.", "螺旋桨转速与桨距控制器件"),
        ("23.1153", "Propeller feathering controls.", "螺旋桨顺桨控制器件"),
        ("23.1155", "Turbine engine reverse thrust and propeller pitch settings below the flight regime.", "涡轮发动机反推与飞行状态以下的螺旋桨桨距设定"),
        ("23.1157", "Carburetor air temperature controls.", "汽化器空气温度控制器件"),
        ("23.1163", "Powerplant accessories.", "动力装置附件"),
        ("23.1165", "Engine ignition systems.", "发动机点火系统"),
        ("23.1181", "Designated fire zones; regions included.", "指定防火区；所含区域"),
        ("23.1182", "Nacelle areas behind firewalls.", "防火墙之后的短舱区域"),
        ("23.1183", "Lines and fittings and components.", "导管、接头与部件"),
        ("23.1189", "Shutoff means.", "切断装置"),
        ("23.1191", "Firewalls.", "防火墙"),
        ("23.1192", "Engine accessory compartment diaphragm.", "发动机附件舱隔板"),
        ("23.1193", "Cowling and nacelle.", "整流罩与短舱"),
        ("23.1195", "Fire extinguishing systems.", "灭火系统"),
        ("23.1197", "Fire extinguishing agents.", "灭火剂"),
        ("23.1199", "Extinguishing agent containers.", "灭火剂容器"),
        ("23.1201", "Fire extinguishing system materials.", "灭火系统材料"),
        ("23.1203", "Fire detector system.", "火警探测系统"),
    ]),
    ("Subpart F - Equipment", [
        ("23.1301", "Function and installation.", "功能与安装"),
        ("23.1303", "Flight and navigation instruments.", "飞行与导航仪表"),
        ("23.1305", "Powerplant instruments.", "动力装置仪表"),
        ("23.1306", "Electrical and electronic system lightning protection.", "电气与电子系统雷电防护"),
        ("23.1307", "Miscellaneous equipment.", "其他设备"),
        ("23.1308", "High-Intensity Radiated Fields (HIRF) Protection.", "高强度辐射场（HIRF）防护"),
        ("23.1309", "Equipment systems and installations.", "设备系统与安装"),
        ("23.1310", "Power source capacity and distribution.", "电源容量与分配"),
        ("23.1311", "Electronic display instrument systems.", "电子显示仪表系统"),
        ("23.1321", "Arrangement and visibility.", "布置与可视性"),
        ("23.1322", "Warning, caution, and advisory lights.", "警告灯、警戒灯与提示灯"),
        ("23.1323", "Airspeed indicating system.", "空速指示系统"),
        ("23.1325", "Static air vent system.", "静压通气系统"),
        ("23.1326", "Pitot heat indication systems.", "空速管加温指示系统"),
        ("23.1327", "Magnetic direction indicator.", "磁航向指示器"),
        ("23.1329", "Automatic pilot system.", "自动驾驶系统"),
        ("23.1331", "Instruments using a power supply.", "使用电源的仪表"),
        ("23.1335", "Flight director instrument.", "飞行指引仪"),
        ("23.1337", "Powerplant instruments.", "动力装置仪表（细节要求）"),
        ("23.1351", "General.", "总则（电气系统与设备）"),
        ("23.1353", "Storage battery design and installation.", "蓄电池设计与安装"),
        ("23.1357", "Circuit protective devices.", "电路保护装置"),
        ("23.1359", "Electrical system fire protection.", "电气系统防火"),
        ("23.1361", "Master switch arrangement.", "总开关布置"),
        ("23.1365", "Electric cables.", "电缆"),
        ("23.1367", "Switches.", "开关"),
        ("23.1381", "Instrument lights.", "仪表照明灯"),
        ("23.1383", "Landing lights.", "着陆灯"),
        ("23.1385", "Position light system installation.", "航行灯系统安装"),
        ("23.1387", "Position light system dihedral angles.", "航行灯系统上反角"),
        ("23.1389", "Position light distribution and intensities.", "航行灯配光与强度"),
        ("23.1391", "Minimum intensities in the horizontal plane of forward and rear position lights.", "前、后航行灯在水平面内的最小强度"),
        ("23.1393", "Minimum intensities in any vertical plane [of position lights.]", "[航行灯]在任一垂直面内的最小强度"),
        ("23.1395", "Maximum intensities in overlapping beams of forward and rear position lights.", "前、后航行灯重叠光束的最大强度"),
        ("23.1397", "Color specifications.", "颜色规范"),
        ("23.1399", "Riding light.", "锚泊灯"),
        ("23.1401", "Anticollision light system.", "防撞灯系统"),
        ("23.1411", "Accessibility.", "可达性"),
        ("23.1413", "Removed.", "已删除"),
        ("23.1415", "Ditching equipment.", "水上迫降设备"),
        ("23.1416", "Pneumatic de-icer boot system.", "气动除冰套系统"),
        ("23.1419", "Deicers.", "除冰装置"),
        ("23.1431", "Electronic equipment.", "电子设备"),
        ("23.1435", "Hydraulic systems.", "液压系统"),
        ("23.1437", "Accessories for multiengine airplanes.", "多发飞机的附件"),
        ("23.1438", "Pressurization and pneumatic systems.", "增压系统与气动系统"),
        ("23.1441", "Oxygen equipment and supply.", "氧气设备与供氧"),
        ("23.1443", "Minimum mass flow of supplemental oxygen.", "补充氧气的最小质量流量"),
        ("23.1445", "Oxygen distribution system.", "氧气分配系统"),
        ("23.1447", "Equipment standards for oxygen dispensing units.", "供氧装置的设备标准"),
        ("23.1449", "Means for determining use of oxygen.", "确定用氧量的装置"),
        ("23.1450", "Chemical oxygen generators.", "化学氧气发生器"),
        ("23.1451", "Fire protection for oxygen equipment.", "氧气设备的防火"),
        ("23.1453", "Protection of oxygen equipment from rupture.", "氧气设备破裂防护"),
        ("23.1457", "Cockpit voice recorders.", "驾驶舱话音记录器"),
        ("23.1459", "Flight recorders.", "飞行记录器"),
        ("23.1461", "Equipment containing high energy rotors.", "含高能转子的设备"),
    ]),
    ("Subpart G - Operating Limitations and Information", [
        ("23.1501", "General.", "总则（使用限制与资料）"),
        ("23.1505", "Airspeed limitations.", "空速限制"),
        ("23.1507", "Maneuvering speed.", "机动速度"),
        ("23.1511", "Flap extended speed.", "襟翼放出速度"),
        ("23.1513", "Minimum control speed.", "最小操纵速度"),
        ("23.1519", "Weight and center of gravity.", "重量与重心"),
        ("23.1521", "Powerplant limitations.", "动力装置限制"),
        ("23.1522", "Auxiliary power unit limitations.", "辅助动力装置限制"),
        ("23.1523", "Minimum flight crew.", "最少飞行机组"),
        ("23.1524", "Maximum passenger seating configuration.", "最大旅客座位构型"),
        ("23.1525", "Kinds of operation.", "运行种类"),
        ("23.1527", "Maximum operating altitude.", "最大使用高度"),
        ("23.1529", "Instructions for Continued Airworthiness.", "持续适航文件"),
        ("23.1541", "General.", "总则（标记与标牌）"),
        ("23.1543", "Instrument markings: general.", "仪表标记：总则"),
        ("23.1545", "Airspeed indicator.", "空速指示器"),
        ("23.1547", "Magnetic direction indicator.", "磁航向指示器"),
        ("23.1549", "Powerplant instruments.", "动力装置仪表标记"),
        ("23.1551", "Oil quantity indicator.", "滑油量指示器"),
        ("23.1553", "Fuel quantity indicator.", "燃油量指示器"),
        ("23.1555", "Control markings.", "操纵器件标记"),
        ("23.1557", "Miscellaneous markings and placards.", "其他标记与标牌"),
        ("23.1559", "Operating limitations placard.", "使用限制标牌"),
        ("23.1561", "Safety equipment.", "安全设备"),
        ("23.1563", "Airspeed placards.", "空速标牌"),
        ("23.1567", "Flight maneuver placard.", "飞行机动标牌"),
        ("23.1581", "General.", "总则（飞机飞行手册）"),
        ("23.1583", "Operating limitations.", "使用限制"),
        ("23.1585", "Operating procedures.", "使用程序"),
        ("23.1587", "Performance information.", "性能资料"),
        ("23.1589", "Loading information.", "装载资料"),
    ]),
    ("Appendix A--Simplified Design Load Criteria", [
        ("A23.1", "General.", "总则"),
        ("A23.3", "Special symbols.", "专用符号"),
        ("A23.5", "Certification in more than one category.", "多于一个类别的取证"),
        ("A23.7", "Flight loads.", "飞行载荷"),
        ("A23.9", "Flight conditions.", "飞行情况"),
        ("A23.11", "Control surface loads.", "操纵面载荷"),
        ("A23.13", "Control system loads.", "操纵系统载荷"),
    ]),
    ("Appendix B--Control Surface Loadings", [
        ("B23.1", "General.", "总则"),
        ("B23.11", "Reserved.", "预留"),
    ]),
    ("Appendix C--Basic Landing Conditions", [
        ("C23.1", "Basic landing conditions.", "基本着陆情况"),
    ]),
    ("Appendix D--Wheel Spin-Up Loads", [
        ("D23.1", "Wheel spin-up loads.", "机轮起旋载荷"),
    ]),
    ("Appendix E--[Removed and Reserved.]", [
        ("E23", "Removed and Reserved.", "已删除并预留"),
    ]),
    ("Appendix F--Test Procedure", [
        ("F23", "An acceptable test procedure for self-extinguishing materials for showing compliance with (Sec. 23.853.)",
         "自熄材料的可接受试验程序（用于表明对 §23.853 的符合性）"),
        ("F23.1", "Part I--Acceptable Test Procedure for Self-Extinguishing Materials for Showing Compliance With Sec. Sec. 23.853, 23.855, and 23.1359",
         "第一部分——用于表明对 §23.853、§23.855 与 §23.1359 符合性的自熄材料可接受试验程序"),
        ("F23.2", "Part II--Test Method To Determine the Flammability and Flame Propagation Characteristics of Thermal/Acoustic Insulation Materials",
         "第二部分——测定隔热/隔声材料可燃性与火焰传播特性的试验方法"),
    ]),
    ("Appendix G--Instructions for Continued Airworthiness", [
        ("G23.1", "General.", "总则"),
        ("G23.2", "Format.", "格式"),
        ("G23.3", "Content.", "内容"),
        ("G23.4", "Airworthiness limitations section.", "适航限制章节"),
    ]),
    ("Appendix H--Installation of an Automatic Power Reserve (APR) System", [
        ("H23.1", "General.", "总则"),
        ("H23.2", "(Definitions.)", "定义"),
        ("H23.3", "Reliability and performance requirements.", "可靠性与性能要求"),
        ("H23.4", "Power setting.", "功率设定"),
        ("H23.5", "Powerplant controls--general.", "动力装置控制器件——总则"),
        ("H23.6", "Powerplant instruments.", "动力装置仪表"),
    ]),
    ("Appendix I--Seaplane Loads", [
        ("I23", "(Seaplane loads.)", "水上飞机载荷"),
    ]),
    ("Appendix J--HIRF Envirnoments and Equipment HIRF Test Levels", [
        ("J23", "(HIRF Envirnoments and Equipment HIRF Test Levels)", "HIRF 环境与设备 HIRF 试验等级"),
    ]),
]

SUBPART_CN = {
    "Subpart A - General": "A 分部　总则",
    "Subpart B - Flight": "B 分部　飞行",
    "Subpart C - Structure": "C 分部　结构",
    "Subpart D - Design and Construction": "D 分部　设计与构造",
    "Subpart E - Powerplant": "E 分部　动力装置",
    "Subpart F - Equipment": "F 分部　设备",
    "Subpart G - Operating Limitations and Information": "G 分部　使用限制与资料",
}


def main():
    out = os.path.join(ROOT, "FAR23_条款中文标题表.csv")
    with open(out, "w", encoding="utf-8-sig", newline="") as f:
        w = csv.writer(f)
        w.writerow(["条款号", "英文标题", "中文标题", "所属分部（英文）", "所属分部（中文）"])
        n = 0
        for sub, items in DATA:
            for num, en, zh in items:
                w.writerow([num, en, zh, sub, SUBPART_CN.get(sub, sub)])
                n += 1
    print(f"→ {os.path.basename(out)}  {n} 条")
    return n


if __name__ == "__main__":
    main()
